import { GovernmentScheme, MarketPrice, FarmerProfile } from "./types";

export const DEFAULT_SCHEMES: GovernmentScheme[] = [
  {
    id: "pm-kisan",
    name: "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
    description: "An initiative by the Government of India that provides up to ₹6,000 per year in three equal installments as minimum income support to all small and marginal farmers.",
    eligibility: "All small and marginal landholding farmer families who have cultivable landholding in their names.",
    benefits: "Direct financial assistance of ₹6,000 per annum paid directly into the bank accounts of farmers.",
    link: "https://pmkisan.gov.in/",
    category: "Direct Benefit"
  },
  {
    id: "pmfby",
    name: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    description: "A government-sponsored crop insurance scheme that integrates multiple stakeholders to protect farmers against crop loss due to natural calamities, pests, or diseases.",
    eligibility: "All farmers growing notified crops in notified areas, including sharecroppers and tenant farmers.",
    benefits: "Financial support to stabilize farmer income, cover premium rates as low as 1.5% to 2%, and full insurance coverage.",
    link: "https://pmfby.gov.in/",
    category: "Insurance"
  },
  {
    id: "pmksy",
    name: "Pradhan Mantri Krishi Sinchayee Yojana (PMKSY)",
    description: "Launched to achieve convergence of investments in irrigation, expand cultivable area, and improve on-farm water use efficiency (Har Khet ko Pani & More Crop Per Drop).",
    eligibility: "All categories of farmers who own agricultural land. Special focus on dryland and drought-prone regions.",
    benefits: "Up to 55%-80% subsidy on installing modern micro-irrigation systems like drip and sprinkler networks.",
    link: "https://pmksy.gov.in/",
    category: "Subsidies"
  },
  {
    id: "kcc",
    name: "Kisan Credit Card (KCC) Scheme",
    description: "Provides farmers with timely and hassle-free access to short-term credit for their cultivation, harvest, and farm maintenance requirements at very low interest rates.",
    eligibility: "Owner cultivators, tenant farmers, oral lessees, sharecroppers, and self-help groups of farmers.",
    benefits: "Subsidized interest rate of 4% per annum (after prompt repayment subsidy) on credit limits up to ₹3 Lakhs.",
    link: "https://www.rbi.org.in/",
    category: "Loans"
  },
  {
    id: "subsidised-seeds",
    name: "National Food Security Mission - Seed Distribution Subsidies",
    description: "Provides high-yielding seed varieties, certified seeds of pulses, oilseeds, and cereals to farmers at heavily subsidized rates to boost yield per acre.",
    eligibility: "Marginal and small farmers registered with their local Rythu Seva Kendras / Agriculture offices.",
    benefits: "50% to 75% subsidy on purchasing certified high-yield seed varieties from licensed government depots.",
    link: "https://nfsm.gov.in/",
    category: "Seeds & Fertilisers"
  }
];

export const DEFAULT_MARKET_PRICES: MarketPrice[] = [
  {
    commodity: "Paddy (Rice) - Grade A",
    market: "Warangal Agri Market, Telangana",
    currentPrice: 2250,
    msp: 2203,
    demandTrend: "High",
    priceForecast: [
      { month: "Jul", price: 2250 },
      { month: "Aug", price: 2290 },
      { month: "Sep", price: 2350 },
      { month: "Oct", price: 2200 },
      { month: "Nov", price: 2180 },
      { month: "Dec", price: 2240 }
    ],
    updatedAt: new Date().toISOString()
  },
  {
    commodity: "Cotton (Long Staple)",
    market: "Adilabad Market Yard, Telangana",
    currentPrice: 7100,
    msp: 7020,
    demandTrend: "Medium",
    priceForecast: [
      { month: "Jul", price: 7100 },
      { month: "Aug", price: 7150 },
      { month: "Sep", price: 7300 },
      { month: "Oct", price: 7050 },
      { month: "Nov", price: 6900 },
      { month: "Dec", price: 7080 }
    ],
    updatedAt: new Date().toISOString()
  },
  {
    commodity: "Maize (Corn)",
    market: "Kurnool APMC, Andhra Pradesh",
    currentPrice: 2150,
    msp: 2090,
    demandTrend: "High",
    priceForecast: [
      { month: "Jul", price: 2150 },
      { month: "Aug", price: 2180 },
      { month: "Sep", price: 2240 },
      { month: "Oct", price: 2110 },
      { month: "Nov", price: 2050 },
      { month: "Dec", price: 2120 }
    ],
    updatedAt: new Date().toISOString()
  },
  {
    commodity: "Wheat (Lokwan)",
    market: "Indore Mandi, Madhya Pradesh",
    currentPrice: 2450,
    msp: 2275,
    demandTrend: "Medium",
    priceForecast: [
      { month: "Jul", price: 2450 },
      { month: "Aug", price: 2480 },
      { month: "Sep", price: 2510 },
      { month: "Oct", price: 2550 },
      { month: "Nov", price: 2600 },
      { month: "Dec", price: 2620 }
    ],
    updatedAt: new Date().toISOString()
  },
  {
    commodity: "Groundnut (Pods)",
    market: "Anantapur Market, Andhra Pradesh",
    currentPrice: 6550,
    msp: 6375,
    demandTrend: "High",
    priceForecast: [
      { month: "Jul", price: 6550 },
      { month: "Aug", price: 6620 },
      { month: "Sep", price: 6700 },
      { month: "Oct", price: 6480 },
      { month: "Nov", price: 6390 },
      { month: "Dec", price: 6450 }
    ],
    updatedAt: new Date().toISOString()
  },
  {
    commodity: "Turmeric (Finger)",
    market: "Erode Market, Tamil Nadu",
    currentPrice: 11800,
    msp: 8500,
    demandTrend: "High",
    priceForecast: [
      { month: "Jul", price: 11800 },
      { month: "Aug", price: 12100 },
      { month: "Sep", price: 12500 },
      { month: "Oct", price: 12300 },
      { month: "Nov", price: 11900 },
      { month: "Dec", price: 12200 }
    ],
    updatedAt: new Date().toISOString()
  }
];

export const DEMO_TICKETS = [
  {
    id: "t1",
    title: "Severe Leaf Spot on Cotton Crop",
    description: "My BT cotton plants are about 45 days old. For the past week, dark reddish-brown circular spots have started spreading across lower leaves. Is this fungal, and what should I spray?",
    status: "In Progress",
    farmerName: "Anji Reddy",
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    replies: [
      {
        sender: "expert",
        senderName: "Dr. Ramesh (M.Sc. Agronomy, RSK Officer)",
        message: "Hello Anji Reddy, based on your description, this looks like Alternaria Leaf Spot. It is a fungal disease triggered by recent high humidity. I recommend spraying Copper Oxychloride 50% WP @ 3g per Litre of water, or Mancozeb @ 2.5g/L. Keep the farm clear of weeds to improve air circulation.",
        sentAt: new Date(Date.now() - 3600000 * 20).toISOString()
      }
    ]
  },
  {
    id: "t2",
    title: "Groundwater decline in Rice Nursery",
    description: "Water table has gone from 80 meters to 110 meters deep this month. The borewell output has reduced significantly. How can I sustain my paddy crop or save water?",
    status: "Resolved",
    farmerName: "Devendra Patil",
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    replies: [
      {
        sender: "expert",
        senderName: "Shri Santosh Kumar (Groundwater Board Executive)",
        message: "Dear Devendra, traditional flooding of paddy is highly inefficient when groundwater is dropping. You should immediately adopt the Alternate Wetting and Drying (AWD) irrigation method. This can reduce water usage by up to 30% with no loss in yield. If possible, consider shifting next season to light dryland crops like Maize or Greengram which require 60% less water.",
        sentAt: new Date(Date.now() - 3600000 * 40).toISOString()
      },
      {
        sender: "farmer",
        senderName: "Devendra Patil",
        message: "Thank you, sir! I will install AWD plastic pipes in my field tomorrow.",
        sentAt: new Date(Date.now() - 3600000 * 30).toISOString()
      }
    ]
  }
];

export const REGIONAL_LANGUAGES = [
  { code: "english", label: "English 🇬🇧" },
  { code: "telugu", label: "తెలుగు (Telugu) 🇮🇳" },
  { code: "hindi", label: "हिन्दी (Hindi) 🇮🇳" },
  { code: "tamil", label: "தமிழ் (Tamil) 🇮🇳" },
  { code: "kannada", label: "ಕನ್ನಡ (Kannada) 🇮🇳" },
  { code: "marathi", label: "मराठी (Marathi) 🇮🇳" }
];

export const LANGUAGE_TRANSLATIONS: Record<string, Record<string, string>> = {
  english: {
    appTitle: "KrishiMitra AI",
    tagline: "Voice & SMS Agricultural Intelligence Platform",
    home: "Dashboard",
    cropRec: "Crop Advisory",
    doctor: "AI Crop Doctor",
    voice: "Voice Assistant",
    sms: "SMS Advisory",
    market: "Market Rates",
    schemes: "Govt Schemes",
    expert: "RSK Experts",
    satellite: "Groundwater & Maps",
    admin: "Admin Console",
    welcome: "Welcome back",
    soilHealth: "Soil Health Status",
    activeAlerts: "Active Alerts",
    weather: "Weather Intelligence",
    temp: "Temp",
    humidity: "Humidity",
    wind: "Wind",
    rainProb: "Rain Prob",
    soilMoisture: "Soil Moisture",
    cropHealth: "Crop Health",
    suggest: "AI Suggestion",
    selectLanguage: "Choose Language",
    farmerProfile: "Farmer Profile Details",
    saveProfile: "Save Farmer Profile",
    district: "District",
    village: "Village",
    farmSize: "Farm Size (Acres)",
    soilType: "Soil Type",
    soilPh: "Soil pH Level",
    nitrogen: "Nitrogen (N)",
    phosphorus: "Phosphorus (P)",
    potassium: "Potassium (K)",
    groundwater: "Groundwater Depth (m)",
    irrigation: "Irrigation Available",
    recommendButton: "Generate AI Crop Recommendation",
    diagnoseButton: "Diagnose Disease",
    recording: "Listening...",
    uploadImg: "Upload Leaf/Fruit Image",
    orDescribe: "Or describe crop symptoms in your voice/text:",
    askPlaceholder: "Ask KrishiMitra anything about farming...",
  },
  telugu: {
    appTitle: "కృషిమిత్ర AI",
    tagline: "వాయిస్ & SMS వ్యవసాయ సమాచార వేదిక",
    home: "డాష్‌బోర్డ్",
    cropRec: "పంట సలహాలు",
    doctor: "AI క్రాప్ డాక్టర్",
    voice: "వాయిస్ అసిస్టెంట్",
    sms: "SMS అడ్వైజరీ",
    market: "మార్కెట్ ధరలు",
    schemes: "ప్రభుత్వ పథకాలు",
    expert: "నిపుణుల సంప్రదింపులు",
    satellite: "భూగర్భ జలాలు & పటాలు",
    admin: "అడ్మిన్ ప్యానెల్",
    welcome: "స్వాగతం",
    soilHealth: "నేల ఆరోగ్య స్థితి",
    activeAlerts: "సక్రియ హెచ్చరికలు",
    weather: "వాతావరణ సమాచారం",
    temp: "ఉష్ణోగ్రత",
    humidity: "తేమ",
    wind: "గాలి వేగం",
    rainProb: "వర్షం అవకాశం",
    soilMoisture: "నేల తేమ",
    cropHealth: "పంట ఆరోగ్యం",
    suggest: "AI సూచన",
    selectLanguage: "భాషను ఎంచుకోండి",
    farmerProfile: "రైతు ప్రొఫైల్ వివరాలు",
    saveProfile: "ప్రొఫైల్ సేవ్ చేయి",
    district: "జిల్లా",
    village: "గ్రామం",
    farmSize: "పంట విస్తీర్ణం (ఎకరాలు)",
    soilType: "నేల రకం",
    soilPh: "నేల పిహెచ్ (pH) విలువ",
    nitrogen: "నైట్రోజన్ (N)",
    phosphorus: "భాస్వరం (P)",
    potassium: "పొటాషియం (K)",
    groundwater: "భూగర్భ జలాల లోతు (మీటర్లు)",
    irrigation: "నీటిపారుదల సౌకర్యం ఉందా?",
    recommendButton: "పంట సిఫార్సులను పొందండి",
    diagnoseButton: "వ్యాధి నిర్ధారణ చేయండి",
    recording: "వింటున్నాము...",
    uploadImg: "ఆకు లేదా పండు చిత్రం అప్‌లోడ్ చేయి",
    orDescribe: "లేదా పంట లక్షణాలను మీ వాయిస్/టెక్స్ట్‌లో వివరించండి:",
    askPlaceholder: "వ్యవసాయం గురించి కృషిమిత్రను ఏదైనా అడగండి...",
  },
  hindi: {
    appTitle: "कृषिमित्र AI",
    tagline: "वॉयस और एसएमएस कृषि खुफिया मंच",
    home: "डैशबोर्ड",
    cropRec: "फसल परामर्श",
    doctor: "AI क्रॉप डॉक्टर",
    voice: "वॉयस असिस्टेंट",
    sms: "एसएमएस एडवाइजरी",
    market: "बाजार भाव",
    schemes: "सरकारी योजनाएं",
    expert: "विशेषज्ञ परामर्श",
    satellite: "भूजल और मानचित्र",
    admin: "एडमिन कंसोल",
    welcome: "आपका स्वागत है",
    soilHealth: "मृदा स्वास्थ्य स्थिति",
    activeAlerts: "सक्रिय अलर्ट",
    weather: "मौसम की जानकारी",
    temp: "तापमान",
    humidity: "आर्द्रता",
    wind: "हवा की गति",
    rainProb: "बारिश की संभावना",
    soilMoisture: "मृदा नमी",
    cropHealth: "फसल स्वास्थ्य",
    suggest: "AI सुझाव",
    selectLanguage: "भाषा चुनें",
    farmerProfile: "किसान प्रोफाइल विवरण",
    saveProfile: "प्रोफाइल सुरक्षित करें",
    district: "जिला",
    village: "गांव",
    farmSize: "खेत का आकार (एकड़)",
    soilType: "मिट्टी का प्रकार",
    soilPh: "मिट्टी का pH स्तर",
    nitrogen: "नाइट्रोजन (N)",
    phosphorus: "फास्फोरस (P)",
    potassium: "पोटेशियम (K)",
    groundwater: "भूजल की गहराई (मीटर)",
    irrigation: "सिंचाई उपलब्ध है?",
    recommendButton: "AI फसल अनुशंसा प्राप्त करें",
    diagnoseButton: "रोग का निदान करें",
    recording: "सुन रहा हूँ...",
    uploadImg: "पत्ती/फल की छवि अपलोड करें",
    orDescribe: "या अपनी आवाज़/पाठ में फसल के लक्षणों का वर्णन करें:",
    askPlaceholder: "खेती के बारे में कृषिमित्र से कुछ भी पूछें...",
  },
  tamil: {
    appTitle: "கிருஷிமித்ரா AI",
    tagline: "குரல் & SMS விவசாய தகவல் தளம்",
    home: "டாஷ்போர்டு",
    cropRec: "பயிர் ஆலோசனை",
    doctor: "AI பயிர் மருத்துவர்",
    voice: "குரல் உதவியாளர்",
    sms: "SMS ஆலோசனைகள்",
    market: "சந்தை விலைகள்",
    schemes: "அரசு திட்டங்கள்",
    expert: "நிபுணர் ஆலோசனை",
    satellite: "நிலத்தடி நீர் & வரைபடங்கள்",
    admin: "நிர்வாகி பகுதி",
    welcome: "வரவேற்கிறோம்",
    soilHealth: "மண் வளம்",
    activeAlerts: "செயலில் உள்ள எச்சரிக்கைகள்",
    weather: "வானிலை தகவல்",
    temp: "வெப்பநிலை",
    humidity: "ஈரப்பதம்",
    wind: "காற்றின் வேகம்",
    rainProb: "மழை வாய்ப்பு",
    soilMoisture: "மண் ஈரப்பதம்",
    cropHealth: "பயிர் ஆரோக்கியம்",
    suggest: "AI பரிந்துரை",
    selectLanguage: "மொழியைத் தேர்வுசெய்",
    farmerProfile: "விவசாயி சுயவிவரம்",
    saveProfile: "சுயவிவரத்தைச் சேமி",
    district: "மாவட்டம்",
    village: "கிராமம்",
    farmSize: "பண்ணை அளவு (ஏக்கர்)",
    soilType: "மண் வகை",
    soilPh: "மண் pH அளவு",
    nitrogen: "நைட்ரஜன் (N)",
    phosphorus: "பாஸ்பரஸ் (P)",
    potassium: "பொட்டாசியம் (K)",
    groundwater: "நிலத்தடி நீர் ஆழம் (மீ)",
    irrigation: "பாசனம் கிடைக்கிறதா?",
    recommendButton: "பயிர் ஆலோசனையை உருவாக்கு",
    diagnoseButton: "நோயைக் கண்டறி",
    recording: "கேட்கிறது...",
    uploadImg: "இலை/பழத்தின் படத்தை பதிவேற்றவும்",
    orDescribe: "அல்லது பயிர் அறிகுறிகளை உங்கள் குரல்/உரையில் விவரிக்கவும்:",
    askPlaceholder: "விவசாயத்தைப் பற்றி கிருஷிமித்ராவிடம் கேளுங்கள்...",
  }
};
